initialization
initializeDigitButtons
   "instantiate the digit buttons"
   button0 := self newButton.
   button1 := self newButton.
   button2 := self newButton.
   button3 := self newButton.
   button4 := self newButton.
   button5 := self newButton.
   button6 := self newButton.
   button7 := self newButton.
   button8 := self newButton.
   button9 := self newButton.

   self defineDigitButtons